-- What is the total revenue generated by the platform?
SELECT
COUNT(*) AS total_subscriptions, SUM(Total_Revenue) AS total_revenue, ROUND(AVG(Total_Revenue),2) AS avg_revenue_per_customer FROM subscriptions;

-- Which programs generate the highest revenue?
SELECT Program_Name, COUNT(*) AS customers, SUM(Total_Revenue) AS total_revenue FROM subscriptions GROUP BY Program_Name ORDER BY total_revenue DESC;

-- How much revenue comes from renewed vs non-renewed customers?
SELECT Renewed, COUNT(*) AS customers, SUM(Total_Revenue) AS total_revenue FROM subscriptions GROUP BY Renewed;

-- What is the average revenue generated per customer?
SELECT ROUND( SUM(Total_Revenue) / COUNT(DISTINCT Customer_ID), 2) AS avg_revenue_generated_per_customer FROM subscriptions;

-- Which programs create the highest-value customers?
SELECT Program_Name, ROUND(AVG(Total_Revenue),2) AS avg_clv FROM subscriptions GROUP BY Program_Name ORDER BY avg_clv DESC;